# Generated by Django 4.2.3 on 2023-07-11 12:23

import app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brands',
            field=models.CharField(choices=[('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche'), ('redmi', 'Redmi'), ('samsung', 'Samsung'), ('itel', 'Itel'), ('motorola', 'Motorola'), ('iphone', 'Iphone'), ('umidigi', 'Umidigi'), ('goole pixel', 'Google Pixel'), ('infinix', 'Infinix'), ('tecno', 'Tecno'), ('xaiomi', 'Xaiomi'), ('oppo', 'Oppo'), ('vivo', 'Vivo'), ('blackberry', 'BlackBerry'), ('nokia', 'Nokia'), ('poco', 'Poco'), ('lg', 'LG'), ('samsung', 'Samsung'), ('sonic', 'Sonic'), ('thermacool', 'Thermacool')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default='black', max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to=app.utils.user_listing_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('solar', 'Solar'), ('electricity', 'Electricity')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
