# Generated by Django 4.2.3 on 2023-07-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='body_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('car', 'Car'), ('Phone', 'Phone'), ('electronics', 'Electronics')], default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_type',
            field=models.CharField(choices=[('private party', 'Private Party'), ('public party', 'Public Party')], default='', max_length=24),
            preserve_default=False,
        ),
    ]
